// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0FHvo6DtQ13GNbz_Ik9GBRPTOsWwc0cY',
    appId: '1:184030789221:web:87d6f3ec1330cad350108c',
    messagingSenderId: '184030789221',
    projectId: 'comlabmanagement',
    authDomain: 'comlabmanagement.firebaseapp.com',
    storageBucket: 'comlabmanagement.appspot.com',
    measurementId: 'G-QBEDVY4RVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeYzau3CcJ0u_Kw1dU355_bHrvLi6iP3k',
    appId: '1:184030789221:android:e73b60ba3d05b47450108c',
    messagingSenderId: '184030789221',
    projectId: 'comlabmanagement',
    storageBucket: 'comlabmanagement.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_-QYL5rMj5HPf9xEp45Fxf82iq4U6ZfM',
    appId: '1:184030789221:ios:1eda09260edc513050108c',
    messagingSenderId: '184030789221',
    projectId: 'comlabmanagement',
    storageBucket: 'comlabmanagement.appspot.com',
    iosClientId: '184030789221-54l56aj6av76iq7rhfjcgnhls50pd9ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.bupolangui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_-QYL5rMj5HPf9xEp45Fxf82iq4U6ZfM',
    appId: '1:184030789221:ios:1eda09260edc513050108c',
    messagingSenderId: '184030789221',
    projectId: 'comlabmanagement',
    storageBucket: 'comlabmanagement.appspot.com',
    iosClientId: '184030789221-54l56aj6av76iq7rhfjcgnhls50pd9ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.bupolangui',
  );
}
